version: "3"
services:
  nginx:
    container_name: nginx
    image: clientimg
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=locahost

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure:10
